begin;

-- ZETA WorkTalk foundation
-- This migration only creates worktalk_* objects and does not alter legacy chat_* tables.

create table if not exists public.worktalk_rooms (
  id bigint generated by default as identity primary key,
  room_type text not null check (room_type in ('direct', 'group', 'team', 'idea', 'approval')),
  title text not null default '',
  team_key text,
  created_by uuid references public.profiles(id) on delete set null default auth.uid(),
  is_fixed boolean not null default false,
  is_archived boolean not null default false,
  archived_at timestamptz,
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.worktalk_room_members (
  room_id bigint not null references public.worktalk_rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete restrict,
  member_role text not null default 'member'
    check (member_role in ('owner', 'member', 'viewer')),
  notifications_enabled boolean not null default true,
  is_pinned boolean not null default false,
  sort_order integer not null default 0,
  joined_at timestamptz not null default now(),
  left_at timestamptz,
  last_read_message_id bigint,
  last_read_at timestamptz,
  primary key (room_id, user_id)
);

create table if not exists public.worktalk_messages (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.worktalk_rooms(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null default auth.uid(),
  sender_name text not null,
  sender_team text,
  message_type text not null default 'text'
    check (message_type in ('text', 'file', 'system', 'document')),
  body text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.worktalk_room_members
  drop constraint if exists worktalk_room_members_last_read_message_id_fkey;

alter table public.worktalk_room_members
  add constraint worktalk_room_members_last_read_message_id_fkey
  foreign key (last_read_message_id)
  references public.worktalk_messages(id)
  on delete set null;

create table if not exists public.worktalk_files (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.worktalk_rooms(id) on delete cascade,
  message_id bigint not null references public.worktalk_messages(id) on delete cascade,
  storage_path text not null unique,
  original_name text not null,
  mime_type text,
  size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 31457280),
  uploaded_by uuid references public.profiles(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create table if not exists public.worktalk_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade default auth.uid(),
  endpoint text not null,
  p256dh text not null,
  auth_key text not null,
  device_label text,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

create index if not exists idx_worktalk_rooms_last_message
  on public.worktalk_rooms (is_archived, last_message_at desc);

create unique index if not exists idx_worktalk_fixed_room_key_unique
  on public.worktalk_rooms (room_type, team_key)
  where team_key is not null;

create index if not exists idx_worktalk_room_members_user
  on public.worktalk_room_members (user_id, left_at, room_id);

create index if not exists idx_worktalk_messages_room_created
  on public.worktalk_messages (room_id, created_at desc, id desc);

create index if not exists idx_worktalk_messages_body_search
  on public.worktalk_messages using gin (to_tsvector('simple', body));

create index if not exists idx_worktalk_files_room_created
  on public.worktalk_files (room_id, created_at desc);

create index if not exists idx_worktalk_files_name_search
  on public.worktalk_files using gin (to_tsvector('simple', original_name));

create or replace function public.worktalk_is_privileged()
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select exists (
    select 1
    from public.profiles profile
    where profile.id = auth.uid()
      and profile.role in ('admin', 'executive')
  );
$function$;

create or replace function public.worktalk_is_room_member(target_room_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select exists (
    select 1
    from public.worktalk_room_members member
    where member.room_id = target_room_id
      and member.user_id = auth.uid()
      and member.left_at is null
  );
$function$;

create or replace function public.worktalk_can_view_room(target_room_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select public.worktalk_is_privileged()
    or public.worktalk_is_room_member(target_room_id);
$function$;

create or replace function public.worktalk_can_manage_room(target_room_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $function$
  select public.worktalk_is_privileged()
    or exists (
      select 1
      from public.worktalk_rooms room
      join public.worktalk_room_members member
        on member.room_id = room.id
      where room.id = target_room_id
        and room.room_type = 'group'
        and room.created_by = auth.uid()
        and member.user_id = auth.uid()
        and member.left_at is null
    );
$function$;

create or replace function public.worktalk_create_direct_room(target_user_id uuid)
returns bigint
language plpgsql
security definer
set search_path = public
as $function$
declare
  existing_room_id bigint;
  new_room_id bigint;
  current_profile public.profiles%rowtype;
  target_profile public.profiles%rowtype;
begin
  if target_user_id is null or target_user_id = auth.uid() then
    raise exception 'A different user is required.';
  end if;

  select * into current_profile from public.profiles where id = auth.uid();
  select * into target_profile from public.profiles where id = target_user_id;

  if current_profile.id is null or target_profile.id is null then
    raise exception 'Profile was not found.';
  end if;

  select room.id
  into existing_room_id
  from public.worktalk_rooms room
  where room.room_type = 'direct'
    and room.is_archived = false
    and (
      select count(*)
      from public.worktalk_room_members member
      where member.room_id = room.id
        and member.left_at is null
    ) = 2
    and exists (
      select 1 from public.worktalk_room_members member
      where member.room_id = room.id and member.user_id = auth.uid() and member.left_at is null
    )
    and exists (
      select 1 from public.worktalk_room_members member
      where member.room_id = room.id and member.user_id = target_user_id and member.left_at is null
    )
  limit 1;

  if existing_room_id is not null then
    return existing_room_id;
  end if;

  insert into public.worktalk_rooms (room_type, title, created_by)
  values ('direct', '', auth.uid())
  returning id into new_room_id;

  insert into public.worktalk_room_members (room_id, user_id, member_role)
  values
    (new_room_id, auth.uid(), 'owner'),
    (new_room_id, target_user_id, 'member');

  return new_room_id;
end;
$function$;

create or replace function public.worktalk_create_group_room(
  room_title text,
  member_ids uuid[]
)
returns bigint
language plpgsql
security definer
set search_path = public
as $function$
declare
  new_room_id bigint;
begin
  if nullif(btrim(room_title), '') is null then
    raise exception 'Room title is required.';
  end if;

  if member_ids is null or cardinality(member_ids) < 1 then
    raise exception 'At least one member is required.';
  end if;

  insert into public.worktalk_rooms (room_type, title, created_by)
  values ('group', btrim(room_title), auth.uid())
  returning id into new_room_id;

  insert into public.worktalk_room_members (room_id, user_id, member_role)
  values (new_room_id, auth.uid(), 'owner');

  insert into public.worktalk_room_members (room_id, user_id, member_role)
  select new_room_id, member_id, 'member'
  from unnest(member_ids) member_id
  where member_id <> auth.uid()
    and exists (select 1 from public.profiles profile where profile.id = member_id)
  on conflict (room_id, user_id) do nothing;

  return new_room_id;
end;
$function$;

create or replace function public.worktalk_send_message(
  target_room_id bigint,
  message_body text
)
returns bigint
language plpgsql
security definer
set search_path = public
as $function$
declare
  profile_row public.profiles%rowtype;
  new_message_id bigint;
begin
  if not public.worktalk_is_room_member(target_room_id) then
    raise exception 'Only room members may send messages.';
  end if;

  if nullif(btrim(message_body), '') is null then
    raise exception 'Message body is required.';
  end if;

  select * into profile_row from public.profiles where id = auth.uid();

  insert into public.worktalk_messages (
    room_id,
    sender_id,
    sender_name,
    sender_team,
    body
  )
  values (
    target_room_id,
    auth.uid(),
    coalesce(profile_row.name, ''),
    profile_row.team,
    btrim(message_body)
  )
  returning id into new_message_id;

  update public.worktalk_rooms
  set last_message_at = now(), updated_at = now()
  where id = target_room_id;

  update public.worktalk_room_members
  set last_read_message_id = new_message_id, last_read_at = now()
  where room_id = target_room_id and user_id = auth.uid();

  return new_message_id;
end;
$function$;

create or replace function public.worktalk_mark_room_read(
  target_room_id bigint,
  target_message_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  resolved_message_id bigint;
begin
  if not public.worktalk_is_room_member(target_room_id) then
    raise exception 'Only room members may mark messages as read.';
  end if;

  if target_message_id is null then
    select max(id) into resolved_message_id
    from public.worktalk_messages
    where room_id = target_room_id;
  else
    select id into resolved_message_id
    from public.worktalk_messages
    where room_id = target_room_id and id = target_message_id;
  end if;

  update public.worktalk_room_members
  set last_read_message_id = resolved_message_id, last_read_at = now()
  where room_id = target_room_id and user_id = auth.uid();
end;
$function$;

create or replace function public.worktalk_set_room_notifications(
  target_room_id bigint,
  enabled boolean
)
returns void
language sql
security definer
set search_path = public
as $function$
  update public.worktalk_room_members
  set notifications_enabled = enabled
  where room_id = target_room_id
    and user_id = auth.uid()
    and left_at is null;
$function$;

create or replace function public.worktalk_sync_fixed_rooms()
returns void
language plpgsql
security definer
set search_path = public
as $function$
begin
  if not public.worktalk_is_privileged() then
    raise exception 'Administrator or executive access required.';
  end if;

  -- NEXUS 기본 고정방은 전 임직원 공용 방 3개와 아이디어 소통방만 유지한다.
  -- profiles.team 전체를 기준으로 부서별 방을 자동 생성하지 않는다.
  insert into public.worktalk_rooms (
    room_type,
    title,
    team_key,
    is_fixed,
    created_by
  )
  values
    ('team', '관리/영업-전임직원', '__company_admin_sales__', true, auth.uid()),
    ('team', '생산-전임직원', '__company_production__', true, auth.uid()),
    ('team', '개발-전임직원', '__company_development__', true, auth.uid()),
    ('idea', '아이디어 소통방', '__all__', true, auth.uid())
  on conflict (room_type, team_key) where team_key is not null
  do update set
    title = excluded.title,
    is_fixed = true,
    is_archived = false,
    archived_at = null,
    updated_at = now();

  insert into public.worktalk_room_members (room_id, user_id, member_role)
  select room.id, profile.id, 'member'
  from public.worktalk_rooms room
  cross join public.profiles profile
  where room.team_key in (
    '__company_admin_sales__',
    '__company_production__',
    '__company_development__',
    '__all__'
  )
  on conflict (room_id, user_id)
  do update set left_at = null;
end;
$function$;

alter table public.worktalk_rooms enable row level security;
alter table public.worktalk_room_members enable row level security;
alter table public.worktalk_messages enable row level security;
alter table public.worktalk_files enable row level security;
alter table public.worktalk_push_subscriptions enable row level security;

grant select on public.worktalk_rooms to authenticated;
grant select on public.worktalk_room_members to authenticated;
grant select on public.worktalk_messages to authenticated;
grant select on public.worktalk_files to authenticated;
grant select, insert, update, delete on public.worktalk_push_subscriptions to authenticated;

grant execute on function public.worktalk_is_privileged() to authenticated;
grant execute on function public.worktalk_is_room_member(bigint) to authenticated;
grant execute on function public.worktalk_can_view_room(bigint) to authenticated;
grant execute on function public.worktalk_can_manage_room(bigint) to authenticated;
grant execute on function public.worktalk_create_direct_room(uuid) to authenticated;
grant execute on function public.worktalk_create_group_room(text, uuid[]) to authenticated;
grant execute on function public.worktalk_send_message(bigint, text) to authenticated;
grant execute on function public.worktalk_mark_room_read(bigint, bigint) to authenticated;
grant execute on function public.worktalk_set_room_notifications(bigint, boolean) to authenticated;
grant execute on function public.worktalk_sync_fixed_rooms() to authenticated;

drop policy if exists "worktalk_rooms_select_viewer" on public.worktalk_rooms;
create policy "worktalk_rooms_select_viewer"
on public.worktalk_rooms
for select
to authenticated
using (public.worktalk_can_view_room(id));

drop policy if exists "worktalk_members_select_viewer" on public.worktalk_room_members;
create policy "worktalk_members_select_viewer"
on public.worktalk_room_members
for select
to authenticated
using (public.worktalk_can_view_room(room_id));

drop policy if exists "worktalk_messages_select_viewer" on public.worktalk_messages;
create policy "worktalk_messages_select_viewer"
on public.worktalk_messages
for select
to authenticated
using (public.worktalk_can_view_room(room_id));

drop policy if exists "worktalk_files_select_viewer" on public.worktalk_files;
create policy "worktalk_files_select_viewer"
on public.worktalk_files
for select
to authenticated
using (public.worktalk_can_view_room(room_id));

drop policy if exists "worktalk_push_select_own" on public.worktalk_push_subscriptions;
create policy "worktalk_push_select_own"
on public.worktalk_push_subscriptions
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "worktalk_push_insert_own" on public.worktalk_push_subscriptions;
create policy "worktalk_push_insert_own"
on public.worktalk_push_subscriptions
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "worktalk_push_update_own" on public.worktalk_push_subscriptions;
create policy "worktalk_push_update_own"
on public.worktalk_push_subscriptions
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "worktalk_push_delete_own" on public.worktalk_push_subscriptions;
create policy "worktalk_push_delete_own"
on public.worktalk_push_subscriptions
for delete
to authenticated
using (user_id = auth.uid());

insert into storage.buckets (id, name, public, file_size_limit)
values ('worktalk-files', 'worktalk-files', false, 31457280)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit;

drop policy if exists "worktalk_storage_insert_member" on storage.objects;
create policy "worktalk_storage_insert_member"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'worktalk-files'
  and (storage.foldername(name))[2] = auth.uid()::text
  and public.worktalk_is_room_member(((storage.foldername(name))[1])::bigint)
);

drop policy if exists "worktalk_storage_select_viewer" on storage.objects;
create policy "worktalk_storage_select_viewer"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'worktalk-files'
  and public.worktalk_can_view_room(((storage.foldername(name))[1])::bigint)
);

do $realtime$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'worktalk_messages'
  ) then
    alter publication supabase_realtime add table public.worktalk_messages;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'worktalk_room_members'
  ) then
    alter publication supabase_realtime add table public.worktalk_room_members;
  end if;
end
$realtime$;

insert into public.worktalk_rooms (
  room_type,
  title,
  team_key,
  is_fixed,
  created_by
)
values
  ('team', '관리/영업-전임직원', '__company_admin_sales__', true, null),
  ('team', '생산-전임직원', '__company_production__', true, null),
  ('team', '개발-전임직원', '__company_development__', true, null),
  ('idea', '아이디어 소통방', '__all__', true, null)
on conflict (room_type, team_key) where team_key is not null
do update set
  title = excluded.title,
  is_fixed = true,
  is_archived = false,
  archived_at = null,
  updated_at = now();

insert into public.worktalk_room_members (
  room_id,
  user_id,
  member_role
)
select
  room.id,
  profile.id,
  'member'
from public.worktalk_rooms room
cross join public.profiles profile
where room.team_key in (
  '__company_admin_sales__',
  '__company_production__',
  '__company_development__',
  '__all__'
)
on conflict (room_id, user_id)
do update set left_at = null;

commit;
