begin;

create table if not exists public.worktalk_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  room_id bigint not null references public.worktalk_rooms(id) on delete cascade,
  message_id bigint not null references public.worktalk_messages(id) on delete cascade,
  sender_id uuid references public.profiles(id) on delete set null,
  sender_name text not null default 'WorkTalk',
  title text not null,
  body text not null default '',
  notification_type text not null default 'message'
    check (notification_type in ('message', 'file', 'system', 'document')),
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, message_id)
);

create index if not exists idx_worktalk_notifications_user_unread
  on public.worktalk_notifications (user_id, read_at, created_at desc);

alter table public.worktalk_notifications enable row level security;

grant select, update, delete on public.worktalk_notifications
to authenticated;

drop policy if exists "worktalk_notifications_select_own"
on public.worktalk_notifications;
create policy "worktalk_notifications_select_own"
on public.worktalk_notifications
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "worktalk_notifications_update_own"
on public.worktalk_notifications;
create policy "worktalk_notifications_update_own"
on public.worktalk_notifications
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "worktalk_notifications_delete_own"
on public.worktalk_notifications;
create policy "worktalk_notifications_delete_own"
on public.worktalk_notifications
for delete
to authenticated
using (user_id = auth.uid());

create or replace function public.worktalk_create_message_notifications()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$
begin
  insert into public.worktalk_notifications (
    user_id,
    room_id,
    message_id,
    sender_id,
    sender_name,
    title,
    body,
    notification_type
  )
  select
    member.user_id,
    new.room_id,
    new.id,
    new.sender_id,
    new.sender_name,
    case
      when new.message_type = 'file' then new.sender_name || '님이 파일을 보냈습니다.'
      when new.message_type = 'system' then '대화방 안내'
      else new.sender_name || '님의 새 메시지'
    end,
    left(new.body, 180),
    case
      when new.message_type = 'file' then 'file'
      when new.message_type = 'system' then 'system'
      when new.message_type = 'document' then 'document'
      else 'message'
    end
  from public.worktalk_room_members member
  where member.room_id = new.room_id
    and member.left_at is null
    and member.notifications_enabled = true
    and member.user_id is distinct from new.sender_id
  on conflict (user_id, message_id) do nothing;

  return new;
end;
$function$;

drop trigger if exists trg_worktalk_message_notifications
on public.worktalk_messages;

create trigger trg_worktalk_message_notifications
after insert on public.worktalk_messages
for each row
execute function public.worktalk_create_message_notifications();

create or replace function public.worktalk_mark_room_read(
  target_room_id bigint,
  target_message_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
declare
  resolved_message_id bigint;
begin
  if not public.worktalk_is_room_member(target_room_id) then
    raise exception 'Only room members may mark messages as read.';
  end if;

  if target_message_id is null then
    select max(id) into resolved_message_id
    from public.worktalk_messages
    where room_id = target_room_id;
  else
    select id into resolved_message_id
    from public.worktalk_messages
    where room_id = target_room_id
      and id = target_message_id;
  end if;

  update public.worktalk_room_members
  set
    last_read_message_id = case
      when resolved_message_id is null then last_read_message_id
      when last_read_message_id is null then resolved_message_id
      else greatest(last_read_message_id, resolved_message_id)
    end,
    last_read_at = now()
  where room_id = target_room_id
    and user_id = auth.uid()
    and left_at is null;

  update public.worktalk_notifications
  set read_at = coalesce(read_at, now())
  where user_id = auth.uid()
    and room_id = target_room_id
    and read_at is null
    and (
      resolved_message_id is null
      or message_id <= resolved_message_id
    );
end;
$function$;

create or replace function public.worktalk_mark_notification_read(
  target_notification_id bigint
)
returns void
language sql
security definer
set search_path = public
as $function$
  update public.worktalk_notifications
  set read_at = coalesce(read_at, now())
  where id = target_notification_id
    and user_id = auth.uid();
$function$;

create or replace function public.worktalk_mark_all_notifications_read()
returns void
language sql
security definer
set search_path = public
as $function$
  update public.worktalk_notifications
  set read_at = now()
  where user_id = auth.uid()
    and read_at is null;
$function$;

grant execute on function public.worktalk_mark_notification_read(bigint)
to authenticated;
grant execute on function public.worktalk_mark_all_notifications_read()
to authenticated;

do $realtime$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'worktalk_notifications'
  ) then
    alter publication supabase_realtime
      add table public.worktalk_notifications;
  end if;
end
$realtime$;

commit;
