begin;

create table if not exists public.worktalk_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_worktalk_push_subscriptions_user
  on public.worktalk_push_subscriptions (user_id);

alter table public.worktalk_push_subscriptions enable row level security;

grant select, delete on public.worktalk_push_subscriptions to authenticated;

drop policy if exists "worktalk_push_subscriptions_select_own"
on public.worktalk_push_subscriptions;
create policy "worktalk_push_subscriptions_select_own"
on public.worktalk_push_subscriptions
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "worktalk_push_subscriptions_delete_own"
on public.worktalk_push_subscriptions;
create policy "worktalk_push_subscriptions_delete_own"
on public.worktalk_push_subscriptions
for delete
to authenticated
using (user_id = auth.uid());

create or replace function public.worktalk_save_push_subscription(
  subscription_endpoint text,
  subscription_p256dh text,
  subscription_auth text,
  subscription_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $function$
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.';
  end if;

  insert into public.worktalk_push_subscriptions (
    user_id,
    endpoint,
    p256dh,
    auth,
    user_agent
  )
  values (
    auth.uid(),
    subscription_endpoint,
    subscription_p256dh,
    subscription_auth,
    nullif(subscription_user_agent, '')
  )
  on conflict (endpoint) do update
  set
    user_id = excluded.user_id,
    p256dh = excluded.p256dh,
    auth = excluded.auth,
    user_agent = excluded.user_agent,
    updated_at = now();
end;
$function$;

create or replace function public.worktalk_remove_push_subscription(
  subscription_endpoint text
)
returns void
language sql
security definer
set search_path = public
as $function$
  delete from public.worktalk_push_subscriptions
  where endpoint = subscription_endpoint
    and user_id = auth.uid();
$function$;

grant execute on function public.worktalk_save_push_subscription(text, text, text, text)
to authenticated;
grant execute on function public.worktalk_remove_push_subscription(text)
to authenticated;

alter table public.worktalk_notifications
  add column if not exists push_sent_at timestamptz;

create index if not exists idx_worktalk_notifications_push_pending
  on public.worktalk_notifications (sender_id, room_id, push_sent_at, created_at desc);

commit;
